---
title: "Random things from random places"
email: "altnate2000@gmail.com"
description: ""
lang: en
baseurl: ""
# the subpath of your site, e.g. /blog
url: "https://alter2000.github.io"
# the base hostname & protocol for your site, e.g. http://example.com
github_username: alter2000

# Build settings
encoding: "utf-8"
highlighter: rouge
lsi: true
excerpt_separator: "\n\n---\n\n"
incremental: false
markdown: kramdown
theme: minima
safe: true
plugins:
  - jekyll-feed
permalink: "/:categories/:short_year/:month/:title/"

# Liquid settings
error_mode: strict
strict_filters: true
strict_variables: true

include:
  - .htaccess
  - _pages

keep_files:
  - keybase.txt
  - .git

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      author_profile: true
      share: true
      related: true
  # archive layouts
  - scope:
      path: ""
      type: archive
    values:
      layout: single
      toc: true
      author_profile: true
