---
title: "Random things from random places"
email: "jor@ineedanew.pw"
description: >
  I'm Jor, and this is my website, nothing more, nothing less. Nothing is
  regularly scheduled here. Hope you like it!


  If you're looking for a hire, check [this](/resume) out.
lang: en
# the base hostname & protocol for your site, e.g. http://example.com
url: "https://ineedanew.pw"
# the subpath of your site, e.g. /blog
baseurl: ""
author: Jor Bashllari
image: https://github.com/alter2000.png

external:
  # bitbucket: alter2000
  github: alter2000
  gitlab: alter2000
  linkedin: jorba-sh
rss: RSS

# Build settings
encoding: "utf-8"
highlighter: rouge
lsi: true
excerpt_separator: "\n\n---\n\n"
incremental: false
livereload: true
markdown: kramdown
safe: true
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
permalink: "/:categories/:short_year/:title/"
paginate: 6
paginate_path: "/:num/"

# Sass settings
sass:
  style: compressed
# Liquid settings
error_mode: strict
strict_filters: true
strict_variables: true

collections:
  slides:
    output: true
    permalink: /:collection/:name

include:
  - _pages

keep_files:
  - keybase.txt
  - .git
  - slides/

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - tags
  - gemset.nix
  - shell.nix
  - site.hs
  - node_modules
  - package.json
  - package-lock.json
  - assets/vendor/semantic
  - .ghci
  - .cache

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
      sidebar:
        nav: left-sidebar
  - scope:
      path: "_talks"
      type: posts
    values:
      layout: slides
      read_time: false
  # archive layouts
  - scope:
      path: ""
      type: archive
    values:
      layout: single
      toc: true
      sidebar:
        nav: left-sidebar
