---
title: "Random things from random places"
email: "altnate2000@gmail.com"
description: ""
lang: en
baseurl: ""
# the subpath of your site, e.g. /blog
url: "https://alter2000.github.io"
# the base hostname & protocol for your site, e.g. http://example.com
github_username: alter2000

# Build settings
encoding: "utf-8"
highlighter: rouge
lsi: true
excerpt_separator: "\n\n---\n\n"
incremental: false
markdown: kramdown
safe: true
plugins:
  - jekyll-feed
permalink: "/:categories/:short_year/:title/"
paginate: 6
paginate_path: "/:num"

# Sass settings
sass:
  style: compressed
# Liquid settings
error_mode: strict
strict_filters: true
strict_variables: true

include:
  - .htaccess
  - _pages

keep_files:
  - keybase.txt
  - .git

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      sidebar:
        nav: left-sidebar
  # archive layouts
  - scope:
      path: ""
      type: archive
    values:
      layout: single
      toc: true
      sidebar:
        nav: left-sidebar
