---
title: "Random things from random places"
email: "altnate2000@gmail.com"
description: "This is my website, nothing more, nothing less. Nothing is
regularly scheduled here."
lang: en
# the base hostname & protocol for your site, e.g. http://example.com
url: "https://alter2000.github.io"
# the subpath of your site, e.g. /blog
baseurl: ""

external:
  bitbucket: alter2000
  github: alter2000
  gitlab: alter2000


# Build settings
encoding: "utf-8"
highlighter: rouge
lsi: true
excerpt_separator: "\n\n---\n\n"
incremental: false
markdown: kramdown
safe: true
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
permalink: "/:categories/:short_year/:title/"
paginate: 6
paginate_path: "/:num/"

# Sass settings
sass:
  style: compressed
# Liquid settings
error_mode: strict
strict_filters: true
strict_variables: true

collections:
  talks:
    pandoc: true

include:
  - .htaccess
  - _pages

keep_files:
  - keybase.txt
  - .git

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
      sidebar:
        nav: left-sidebar
  - scope:
      path: "_talks"
      type: posts
    values:
      layout: slides
      read_time: false
  # archive layouts
  - scope:
      path: ""
      type: archive
    values:
      layout: single
      toc: true
      sidebar:
        nav: left-sidebar
